HekaTekNYC/HekaTek

- src/components/sparkles/Sparkles.jsx
- src/routes/home/Home.jsx
> sparkles adjustment

- src/components/navigation/navigation.scss
- src/components/product-cards/product-card.scss
- src/routes/products/Products.jsx
- src/routes/products/products.scss
This push is a semi-fix for the header sticking while scrolling through parallax layers.
> scroll effect header fix

- src/components/product-cards/product-card.scss
- src/routes/products/products.scss
- src/routes/services/Services.jsx
- src/routes/services/services.scss
pushing minor responsive changes
> Last commit of the night

- src/components/product-cards/ProductCard.jsx
mobile touch compatibility with hover put in effect
> mobile touch

- package-lock.json
- public/index.html
- src/.htaccess
- src/routes/services/Services.jsx
- src/routes/services/services.scss
- webpack.config.js
Fixed SVG showing up as text/html. Had to do with index.html and webpack. Font is preloading and svg's are correctly being displayed.
> Font & SVG Fix

- public/index.html
- src/App.jsx
- src/components/button/Button.jsx
- src/components/button/button.scss
- src/components/hexagon-icon/hexagon-icon.scss
- src/index.scss
- src/routes/about/About.jsx
- src/routes/about/about.scss
- src/routes/hero/Hero.jsx
- src/routes/home/Home.jsx
- src/routes/home/home.scss
- src/routes/services/services.scss
about us mobile and button reconfiguration
> about us mobile

- src/components/hexagon-icon/hexagon-icon.scss
- src/routes/about/About.jsx
- src/routes/about/about.scss
all image issues and responsiveness fixed and finalized
> V5 about responsiveness

- src/components/button/Button.jsx
- src/components/button/button.scss
- src/components/contact-form/ContactForm.jsx
- src/components/contact-form/contact-form.scss
- src/components/footer/footer.scss
- src/routes/pricing-plans/pricing-plans.scss
- src/routes/products/Products.jsx
final contact form with button connection and modal edit
> contact form connected

- src/routes/about/About.jsx
- src/routes/about/about.scss
about image adjustment with one image - not finalized
> about image adjustment

- package-lock.json
> V5 - build

- src/components/navigation/dropdown/dropdown.scss
- src/components/product-info/product-info.scss
- src/index.scss
- src/routes/products/products.scss
- src/routes/services/services.scss
> V5 - font adjustments

- package-lock.json
- public/index.html
- src/components/button/Button.jsx
- src/components/calendly-modal/Modal.jsx
- src/components/navigation/navigation.scss
- src/routes/about/About.jsx
- src/routes/hero/Hero.jsx
- src/routes/why-us/WhyUs.jsx
All schedule meeting buttons now link to calendly. Changed the on hover navlinks color. Implemented Calendly within the Hero, About, and WhyUs pages. Also created a Modal component for Calendly to override the popup blocker in browser.
> Calendly - Google Meet

- public/index.html
- src/components/contact-form/contact-form.scss
- src/components/footer/footer.scss
- src/routes/hero/hero.scss
- src/routes/pricing-plans/PricingPlans.jsx
- src/routes/products/products.scss
> V5 minor edits

- src/components/footer/Footer.jsx
Github name and email name updated on footer
> Github Email Update

- src/routes/hero/Hero.jsx
Calendly now connected with hekateknyc.com
> Update to Calendly

- src/routes/about/About.jsx
Changed the about sections text.
> Updated About Section

- src/routes/hero/Hero.jsx
- src/routes/pricing-plans/PricingPlans.jsx
Get started button changes on pricing plan and pricing plan adjustments
> Get started connection

- src/routes/why-us/WhyUs.jsx
> Version 5.1

- README.me
> version 6 bug fix

- package.json
> cache clean

- src/data/PricingData.jsx
> pricing correction

- README.me
- src/data/ProductData.jsx
- src/routes/about/About.jsx
- src/routes/hero/Hero.jsx
- src/routes/why-us/WhyUs.jsx
> Grammar & Typos Fixed

- src/routes/pricing-page/PricingPage.jsx
> pricing page

- src/App.jsx
- src/components/footer/footer.scss
- src/index.scss
- src/routes/contact/contact-page.scss
- src/sections/contact-section/contact-section.scss
- src/sections/services-section/services-section.scss
> contact page height

- src/App.jsx
- src/routes/about/AboutPage.jsx
- src/routes/about/about-page.scss
- src/routes/pricing/PricingPage.jsx
- src/routes/pricing/pricing-page.scss
- src/routes/products/ProductsPage.jsx
- src/routes/products/products-page.scss
- src/routes/services/ServicesPage.jsx
- src/routes/services/services-page.scss
Created pricing, about, services, and products
> Pages Created

- src/App.jsx
- src/components/footer/footer.scss
- src/components/layout/Layout.jsx
- src/index.scss
- src/routes/contact/ContactPage.jsx
- src/routes/contact/contact-page.scss
- src/routes/home/home-page.scss
- src/routes/services/services-page.scss
- src/sections/services-section/services-section.scss
layout page created and put into app.jsx. Home page and contact page corrected. Services section reworked for responsiveness
> layout page and homepage adjustments

- src/components/contact-form/contact-form.scss
- src/routes/home/home-page.scss
- src/sections/services-section/services-section.scss
- src/sections/why-us-section/why-us-section.scss
why use and services sections padding and responsiveness corrections
> why us and services sections

- src/components/contact-form/contact-form.scss
- src/routes/contact/ContactPage.jsx
- src/routes/contact/contact-page.scss
contact page completed with responsiveness reconfiguration
> contact page

- package-lock.json
- package.json
- src/components/our-process/OurProcess.jsx
- src/components/our-process/our-process.scss
- src/routes/about/AboutPage.jsx
- src/routes/about/about-page.scss
- src/sections/about-section/AboutSection.jsx
- src/sections/about-section/about-section.scss
completed our-process and media queries
> Our Process

- src/routes/about/AboutPage.jsx
- src/routes/services/ServicesPage.jsx
services page with pulled in components
> about and services page

- src/components/why-choose-us/WhyChooseUs.jsx
- src/components/why-choose-us/why-choose-us.scss
> why choose us

- src/components/button/Button.jsx
- src/components/faq/Faq.jsx
- src/components/faq/faq.scss
- src/components/pricing-card/pricing-card.scss
- src/routes/faq/faq-page.scss
pricing card clean up with scss
> Team pages

- src/components/faq/faq.scss
- src/routes/contact/contact-page.scss
- src/routes/faq/faq-page.scss
- src/routes/pricing/pricing-page.scss
- src/sections/pricing-section/pricing-section.scss
faq and contact page image correction
> faq and contact page correction

- src/data/PricingData.jsx
- src/routes/audit-page/AuditPage.jsx
- src/routes/audit-page/audit-page.scss
as well as get started button on free audit page
> removal of sale price
